export const Color = {
  LIGHT: {
    PRIMARY: '#EB1C24',
    SECONDARY: '#002F67',
    BACKGROUND: '#FFFFFF',
  },
  DARK: {
    PRIMARY: '#EB1C24',
    SECONDARY: '',
    BACKGROUND: '#2E2E2E',
  },
  BLACK: '#222222',
  SHADOW: '#E5E5E5',
  LIGHTSHADOW: '#F5F5F5',
  WHITE: '#FFFFFF',
  GREY: '#707070',
  LIGHTGREY: '#CECECE',
  VERYLIGHTGREY: '#F2F2F3',
  SEMILIGHTGREY: '#EEEEEE',
  DARKGREY: '#1B1B1B',
  SKYBLUE: '#007FFF',
  AQUA: '#C6FBFF',
  ORANGE: '#EE7723',
};
